### ISSUE TITLE
Skin folder suggestion

### ISSUE THREAD

**Issue by nodkrot** [webcomm/magento-boilerplate#110]
Use case: whenever I add extensions to magento the skin files from the extension are located in the js and css folders, so if I want to modify/extend extensions I need to recreate the js file in my theme (boilerplate). Example: /skin/js/{extension dir}/{extension}.js
Then if I run "gulp" the js folder is being rewritten and only script.js is left.

May be you need to add one more layer for js/css/img assets like so: /skin/dist/js, /skin/dist/css and make gulp to output there or something similar (may be additional gulp command).
If I'm missing something let me know.

**Comment by bencorlett** [comment]
There's two ways around this..

1. Change the output paths (i'm not going to in the core because I prefer (2)).
2. Use layout updates to remove the extension's skin files. Then, create your own LESS file which produces the required styles in the most efficient fashion. so the extension's CSS is actually part of your one file. Not as modular, but creates a much more optimised system.

Hope that helps!

**Comment by nodkrot** [comment]
Got you, so for the js the best thing would be is to change the path?

**Comment by bencorlett** [comment]
Umm, yeah probably. I try and consolidate all assets into my client’s single scripts :)

**Comment by nodkrot** [comment]
Thank you, and layout is a good idea, completely forgot

**Comment by bencorlett** [comment]
You’re welcome :) Happy coding.
