### ISSUE TITLE
Amazing starter theme - what direction is it moving in and are you looking for pull requests?

### ISSUE THREAD

**Issue by Buswell** [webcomm/magento-boilerplate#143]
Hi Webcomm,

Absolutely amazing starter theme.    I shudder to think what would happen when I'm developing in Magento without your starter theme to go off!

This is not an issue at all but you wrote "on your vision for how this can be improved" on this github homepage
*(typo? it should be OR not on? - maybe that's the issue)

I'm just wondering what direction you are moving the boilerplate theme in?  I can see you've got a gruntfile in the repo so presumably you used to be on Grunt and have now moved to Gulp? (as the industry has!)

Have you any plans to move the project over to Sass?   It seems to have been decided as the winner in the preprocessor wars and there are a few Bower libraries I really want to use that are Sass only - the Susy grid framework for starters.
If not I think I'll have to do my own Sass fork of this!

Also I made my own local fork with a few changes to the gulpfile - mainly gulp-autoprefixer:  absolutely priceless plugin I have no idea how people work without it.

Now that Magento 2 is out and stable will your next steps be making a Boilerplate for Magento 2?  (haven't done any coding for Mage 2 yet so no idea how much themes will change)

Great work though.   I've taken a few ideas from your project, like gulp-notify, and am using that in my gulpfile on every project I do on other CMSs.  Such a helpful tool

Cheers,
Buswell

**Comment by bencorlett** [comment]
Heya,

So as far as the Magento Boilerplate project goes, I'm moving away from Bootstrap altogether and using Foundation. You can checkout the app skeleton over at [https://github.com/webcomm/magento-boilerplate-app](https://github.com/webcomm/magento-boilerplate-app).

It has a number of huge improvements over the existing boilerplate, particularly with how the boilerplate is installed and managing your themes without duplicating code.

Feel free to check it out!

I haven't launched it officially because I've been too busy to write up documentation. However, it's currently used in over a hundred live websites (that I know of) including [Musos Corner](https://www.musoscorner.com.au), [Early Settler](http://www.earlysettler.com.au) and [Just Hockey](http://www.justhockey.com.au) to name a few.

Regarding Magento 2, I have not explored what I'd like to do here, whether it is worth competing with the built-in (not as good, but sufficient) theming system or not.

I hope this answers your questions!
