### ISSUE TITLE
Homepage and various others working slow

### ISSUE THREAD

**Issue by brandonjjon** [webcomm/magento-boilerplate#78]
HI there,

I've installed this successfully.. however the homepage loads extremely slow on my computer, around 30 seconds probably. As soon as I switch back to default theme the site speeds back to to normal. What could be causing this? And what do you need from me in order to diagnose this issue.

Thanks

**Comment by gnowland** [comment]
I came across this issue too, I think that it would be a good idea to remove livereload or at leas set it to "false" by default in the gulpfile, because a "boilerplate" should be the bare bones, not require me to install a chrome plugin in order to work properly right out-of-the-box.

Just my 2 cents, but I think the inclusion of livereload as a dev dependency extends a bit further beyond the scope of a "boilerplate", typically boilerplates don't dictate what my dev environment should be, that should be up to me.

**Comment by bencorlett** [comment]
I'm okay with this now. If you could put in a PR to change it I'll merge it. 

Sent from my iPhone

Please excuse my brevity

**Comment by gnowland** [comment]
PR sent! Thanks again for this solid boilerplate theme for Magento, I really appreciate the work you put into it.

**Comment by bencorlett** [comment]
Awesome! Thanks for the kind words.
